dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - libgtk-3-dev
      - libglew-dev
script:
  # Link gcc-9 and g++-9 to their standard commands
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++, cmake and ld
  - gcc -v && g++ -v && cmake --version && ld --version

  # Download cocos2d-x-3.17.1
  - wget -O cocos2d-x-3.17.1.tar.gz https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.1.zip
  - unzip cocos2d-x-3.17.1.tar.gz
  # Build the project
  - yes | cocos2d-x-3.17.1/tools/cocos2d-console/bin/cocos compile -p linux
